--- 
title: "Probability, statistics, and the likelihood ratio for non-experts [draft]"
author: "Dr. Harry Gray"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [bib/packages.bib, bib/stats-book.bib]
biblio-style: apalike
link-citations: yes
description: "This book is a learning resource for those who would like to learn more about how probability and statistics are used to evaluate scientific evidence in the courtroom without being subject-matter experts."
always_allow_html: true
---


# Preface {-}

This book produced by the Leverhulme Research Centre for Forensic Science (LRCFS) provides a learning and reference resource for those without statistical expertise on the topic of evaluating forensic science evidence using the likelihood ratio approach. It aims to provide the stepping stones required to become comfortable with likelihood ratio-based evaluations of evidence, as endorsed by the European Network of Forensic Science Institutes, and the Forensic Science Regulator of the UK.

**Accessibility and navigation**. Please note that the text size, font style, and contrast of the book can be changed by clicking the 'A' button on the top tool bar. Alt text is also provided for all images for use with screen readers. Text size can also be made larger by zooming in using the usual Windows Ctrl + plus sign (+) or Mac Cmd + plus sign (+) keyboard shortcuts, or by using your web browser's controls. The table of contents on the left-hand side bar can be used to navigate between sections of the book and the arrows on the right and left-hand sides of the current page can be used to go to the next/previous page. 

Copyright &copy; 2020-2021 [LRCFS](https://www.dundee.ac.uk/leverhulme)

## Why this book? {-}

High quality resources can already be found on this topic, which have been authored by the founders of systematic approaches to forensic evidence evaluation and which have been endorsed by national-level organisations. These include @aitken2010, @puch2012, @roberts2014, @jackson2015, @enfsi2016, @icca2017, and @statsprimer2020. This resource aims to complement and extend the existing texts in the following ways:

1. by providing more examples for each of the core concepts so that learners can see the theory in action

2. by providing worked exercises and solutions for learners to test and reinforce their understanding

3. by providing interactive material (in the online version of this resource) to enhance the learning experience

4. by being based online to allow feedback to be easily given and regularly implemented, and for content updates to be easily made as scientific thinking develops and current practices change - see the sections below on how to contribute.

This book follows the main content from the Royal Statistical Society's Fundamentals of Probability and Statistical Evidence in Criminal Proceedings book [@aitken2010] and then portions of The Logic of Forensic Proof [@roberts2014]. We have also provided motivation for the use of probability and statistics by drawing from the uncertainty communication literature, and in particular adapting the advocated model from @vanderbles2019 to forensic science. Put together, this resource provides an intermediate overview of why and how we use probability and the likelihood ratio for evaluating forensic evidence, including examples and exercises to reinforce understanding.

The interactive examples in the online version of this book can be found as part of an [interactive application](https://lrcfs.dundee.ac.uk/apps/interactive-lr/). This is to provide a standalone resource for those who are not using the book e.g. a wider audience, and also so that those who prefer to use a printed version of this book can still have fast access to the examples they need. 

The content presented here is not a comprehensive guide to the evaluation of all forensic evidence. For example in the UK (as of writing this in August 2020), the numerical evaluation of impression evidence (such as fingerprints) is not widely practised compared to say, how it is done in other jurisdictions such as The Netherlands. In addition, each evidence type is currently at a different stage of scientific understanding. As a result, the exact statistical considerations for each evidence type differ, even if the general evaluation methodology is similar. More information on the state of each type of evidence can be found in the judicial Primers series commissioned by the Royal Society and the Royal Society of Edinburgh [@dnaprimer2017; @gaitprimer2017; @statsprimer2020].

## Who this is for {-}

This book is primarily aimed at judges, but in the UK that covers at least two distinct domains: criminal and civil. The skills required to understand the statistical evidence in both of these domains is sufficiently different to be given separate treatments. This book (as of the current version) is dominated by content to help with forensic evidence in criminal cases. As time progresses and we receive feedback, and in particular if there is demand for it, we may add content to aid understanding of civil applications of statistics too, e.g. epidemiological evidence.

There is a wider audience who might also benefit from this material. This includes legal counsel, students of law, and students of forensic science who are relatively new to statistics and its application in evaluating evidence. Our hope is that this can be an engaging resource to supplement professional development and formal study.

We welcome feedback and contributions so that we can improve the content of this book. See the notes on how to contribute and and how to contact us in the sections below.

## How to contribute {-}

One of the purposes of this book is to be reactive to feedback and be easy to contribute to. We strongly encourage feedback, be it negative or positive, so that we can change what is not working and keep what is working and ensure the book remains fit for purpose. Collaboration from all stakeholders within the criminal justice system is welcomed.

There are three ways to contribute, detailed below.

### Participate in our research studies {-}

We conduct research studies involving this book and its accompanying interactive application. When studies are being run the details for participating will appear here. If you would like to find out more about these studies or wish to register your interest in taking part in future studies, then contact Professor Niamh Nic Daéid using the email address in the section below.

### Email {-}

Do not follow the instructions in this section if you are taking part in our anonymous research study. Instead, use the questions in the survey to communicate your feedback.

Please email Professor Niamh Nic Daéid [n.nicdaeid@dundee.ac.uk] with your feedback on the book, including any thoughts and suggestions for future content. We particularly welcome thoughts of members of the judiciary. When making a contribution, please be sure to reference specific sections of the book so that it can be reviewed efficiently. If you have disagreements with the content then please raise these. Remember to provide your name and affiliation so that you can be added to the list of contributors below.

### Github {-}

If you don't know what 'Github' is, then skip this section.

All of the code to generate this book (and its content) can be found [here on the LRCFS Github](https://github.com/LRCFS/lrcfs-stats-reference-book). 

Please use the Issue function to raise any problems or suggested content changes. If your change is minor and you can do it quickly yourself (e.g. a spelling correction, a minor rewording, etc.) then feel free to make a Pull request.

Any further correspondence can be addressed via email using the details in the section above.

## Acknowledgements {-}

### Funders {-}

Funding was obtained from the David and Claudia Harding foundation and the Leverhulme Trust by Professor Niamh Nic Daéid who is principal investigator for this work. Dr Harry Gray was funded by the David and Claudia Harding foundation, and is a postdoctoral research assistant at LRCFS which is funded by the Leverhulme Trust. Thanks go to these funding bodies, who have made this non-traditional academic output possible. It is our intention that this resource will contribute to raising statistical and probabilistic literacy within forensic science by embracing emerging technology and positively disrupting the traditional way we engage others with statistical ideas.

### Contributors {-}

Mr Roy Mudie at LRCFS has been instrumental in developing the R Shiny application and interactive elements which accompany this book. This allows the html version of this book to contain interactive examples and questions which we hope enhance the users' learning experience. The application can also be used as a standalone tool to engage with other statistical content. Roy has helped with many of the technical issues which have arisen behind the scenes and has helped to visualise some of our examples in a way that is intuitive.

Thanks also to Dr Pat Dugard, Ms Pauline Mack, Dr Joyce Klu, Dr Heather Doran, Dr Emma Comrie, Professor Lucina Hackman, and Professor Niamh Nic Daéid as members of an internal review team at LRCFS. This team provided feedback on the content and appearance of the book which has significantly improved its presentation, conciseness, and clarity.

A special thanks goes to our anonymous research participants who volunteered a large portion of their time to give feedback on this book and the accompanying R Shiny application. This group spanned external practising and academic forensic scientists, research students, and members of the LRCFS Citizen's Jury. Their feedback helped to improve the technical precision of the content as well as showing us where to focus our efforts in order to make the materials more understandable and engaging.

### Software {-}

This book was written using the **bookdown** package [@bookdown2016], which was built on top of R **Rmarkdown** [@rmarkdown2018] and **knitr** [@knitr2015]. This free and well-documented software has allowed this book to be developed hassle-free in a completely reproducible way. Thank you Yihui for your work to support open software and open science.

Other R packages that have been used throughout this book: [@igraph2006; @tidyverse2019; @R-ggthemes; @R-kableExtra]. 

Interactive questions in this book have been made using a self-hosted instance of [h5p](https://h5p.org) Copyright &copy; 2016 Joubel AS. The h5p content is licensed under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) and the code is available under an MIT license (see the [LRCFS Github repository](https://github.com/LRCFS/lrcfs-stats-reference-book)).

## Updates and versions {-}

### About this version (version 1.0) {-}

The book is currently in its version 1.0 release. This means that we have incorporated feedback from external stakeholders and that all content and code is now publicly available.

### Planned versions {-}

Versions in planning:

- Version 1.1 - incorporating feedback and continual improvements

### Update history {-}

04/2020 - Work on the book begins

06/2020 - Application for interactive examples created

08/2020 - First draft of the book

12/2020 - Second draft of the book

03/2021 - Interactive questions and summary sections added

04/2021 - Research study launched

06/2021 - Feedback from research study included

06/2021 - Version 1.0 launched

### Future content {-}

- Comment/Discussion section at the end of each chapter

- Case Assessment and Interpretation protocol introduction

- A Bayesian network primer

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'igraph',
  'ggthemes', 'kableExtra', 'tidyverse'
), 'bib/packages.bib')
```
