# Introduction {#intro}

This book aims to assist non-experts in the method of evaluating forensic scientific evidence known as the likelihood ratio (LR) approach. The LR approach relies upon the theory of probability, statistics, and the application of forensic logic to criminal investigations. To many people (including subject experts), these topics are difficult to understand. This is because they really are difficult to understand; they require demanding and unfamiliar logic, abstract mathematical ideas, and can often produce counter-intuitive conclusions. These challenges lead experts and non-experts alike to a variety of misunderstandings, mistakes, and reasonable disagreements about the exact application of probability theory, and specifically the LR approach, to criminal investigations. Nonetheless, the LR approach is used routinely in forensic investigations worldwide and is presented to non-experts in the courtroom - so it must be understood.

Improving the understanding of the LR approach amongst all of the key actors in the courtroom has clear benefits. For forensic scientists as expert witnesses, mastery of the LR approach will lead to improved communication in the courtroom. This comes with being able to precisely address questions from advocates about the merits and limitations of an LR in the context of a case as well as clearer communication. An improved understanding of the LR approach by advocates unlocks greater value from expert evidence. This is produced by more pertinent questioning and clearer communication to the fact finder. These benefits also hold for judges in their capacity of gatekeeping evidence. As for the fact-finding capacity of a judge, an improved understanding allows for LRs to be considered more robustly. Finally, a greater understanding from all parties allows for more open, equitable, and accurate discussion about the ongoing role of probabilistic methods (including the LR approach) in the criminal justice process.
 
The fundamental question that the LR approach addresses is a useful one for the court. What is the value of scientific evidence after accounting for the assertions made by the prosecution and defence? Although the question has remained the same, the means of answering it have grown more complex over time. This is mostly due to advancements in technology, increasing the types of evidence which can be analysed scientifically and the effectiveness of the scientific methods that are used. Analysis methods for DNA traces for example are now able to detect tiny amounts of DNA and provide value to the court even when there are multiple donors to a DNA mixture. This has not been without significant controversy, due at least in part to its complexity which hinders communication.

This challenge is likely to persist. Recent movements within the forensic science community which aimed to increase its scientific basis have led to more quantitative data generation. More data and a better understanding of that data has led to more computer algorithms for data analysis. Although the performance of algorithms is unparalleled for certain tasks, the complexity of such algorithms raises the difficulty of communicating their accuracy, reliability, and applicability. This is compounded when the internal decision-making of an algorithm is not fully understood. One popular technique within the academic literature of forensic science right now is the use of machine learning for classifying objects based on measurable characteristics. It may not take long until such techniques become commonplace in expert evidence, potentially creating difficulties of communication between experts and non-experts. That communication will be made easier if there is a common baseline level of understanding between all parties within the courtroom. Although centred around the LR approach, the ideas contained in this book are also useful for understanding algorithms that are underpinned by probability. 

This book is organised as follows. In Chapter \@ref(uncertainty) we outline the nature of uncertainty in forensic science, which provides the motivation for using the mathematical tool of describing uncertainty: probability. In Chapter \@ref(probability) we define what probability is and how it is used to quantify uncertainty. In Chapter \@ref(propositions) we show how formalised propositions allow probability to be framed around key disputed facts in order to be applied in forensic investigations. Finally in Chapter \@ref(likelihood-ratio), we show how probability, propositions, and evidence are combined  using the LR approach in order to quantify the value of a piece of scientific evidence in criminal investigations.

Reading through this book and completing the activities it contains will not convert a non-expert in the LR approach into an expert. However, it should provide more insight into the LR approach so that those without statistical expertise can develop their proficiency and agency in managing expert statistical evidence in criminal proceedings.