# Propositions for facts-in-issue {#propositions}

This Chapter introduces propositions

## Facts-in-issue

To motivate the use of propositions, we begin with a discussion about facts-in-issue. Facts-in-issue are the relevant facts of a specific case which are contested by each side of the legal dispute. In criminal trials, this typically manifests as the defence contesting facts which the prosecution have asserted.

There is epistemic uncertainty about the facts-in-issue and so relevant evidence is presented to the court. The fact finder then considers this evidence to determine the truth of the facts-in-issue, and ultimately the outcome of the case. 

It is clear from this that the language and presentation of facts-in-issue must be precise and accurate. The presentation should also be done in a way that allows the fact finder to clearly discriminate between what either side of counsel is asserting. To achieve this, forensic scientists formalise the facts-in-issue into what are known as propositions. 

## Propositions

A proposition is an assertion about a factual state of nature. The 'factual' part of that is key since it means that the assertion is capable of being either true or false. Thus, propositions are capable of either being true or false. Although not always correct, we will speak of propositions as not only **capable of being** either true or false, but **as** being either true or false. 

The truth of propositions does not depend upon people's belief about them (unless the proposition is specifically about their belief). Consider the following:

1. The Earth orbits the Sun.
2. The Earth is flat.

Proposition 1 is true and proposition 2 is false, and we have substantial scientific evidence to prove this. At a certain point of time in history, however, common belief about those propositions was false: people thought that the Sun orbited the Earth, and that the Earth was flat (and some still do...). It was true that the Earth orbits the Sun both before and after humans had enough evidence to believe it was true. 

Propositions can still evoke epistemic uncertainty; they are true or false but we might not know which. In this case we can probabilistically reason about them. Consider another example:

3. Poker Player B is holding an ace in this round.

In this hypothetical poker game, it's self-evident that the proposition is true if Player B is holding an ace and it is false if Player B is not holding an ace. If you are Player B then you will know the truth of this and the proposition is trivial. However, if you are not Player B then you won't know the truth of this; you have epistemic uncertainty.

To play your hand well, you will have to come to a reasonable belief about the probability of this proposition (and others) and make decisions about checking, raising, or folding etc., whilst accounting for this uncertainty. Note that in this example you might **never** know the truth of this proposition. Player B might never turn over their cards nor reveal the answer. The proposition was still either true or false regardless of this.

The truth of some propositions may change as situations change. Consider the following:

4. Boris Johnson's Conservative party govern the UK. 

As of me writing this, the proposition is true. The UK still exists, the Conservative party exist under that same name and are led by Boris Johnson, and his party governs the UK after a landslide general election win. This proposition won't be true forever, and may not even be true by the time you're reading this. It can help to be more specific when formulating propositions to overcome this dependence on time or other factors. Changing the proposition instead to:

5. On 20th May 2020, Boris Johnson's Conservative party govern the UK 

gives a more specific proposition that is now unambigious about the temporal factor which may affect it. However, the proposition is now less general since it only refers to one specific day. Whether this lack of generality is worth the extra specificity or not depends on the question at hand. When the question is provided by investigators and given to forensic scientists, then the scientists have to balance these factors when formulating appropriate propositions. 

## Competing propositions

When formulating propositions from facts-in-issue, the different sides of the adversarial system make different assertions about the circumstances which lead to the same factual observation.

For example, as part of a case there might be a DNA sample at the crime scene which was found to match the DNA profile taken from the suspect after their arrest. The prosecution might assert that the defendant was at the location in which the DNA sample was recovered. The defence, on the other hand, might accept that this is the defendant's DNA but instead assert that it was indirectly transferred there, e.g. from contact with another individual who was provably at the crime scene. Both of these assertions would reasonably lead to the defendant's DNA matching the crime scene sample.

Translating these assertions into propositions gives so-called competing propositions. Competing propositions typically come in pairs, one put forward by each side of legal counsel. They are often denoted as $H_p$ and $H_d$ to represent 'prosecution/defence hypothesis', and we'll use this from now on.

Case scenario: Police were called to the house of a known local drug-dealer after reports by neighbours of a suspected gunshot heard from within. They arrived at the scene to find a middle-aged male, the known drug-dealer, shot dead in a bedroom. A window at the back of the house on the ground floor was found to be smashed, with the glass having fallen towards the inside of the house. They found open death-threats on the deceased's public social media account from two males. The males are known to police, having previously been involved in drug-related crimes too. Both are arrested at their known addresses, at which time Suspect 1 confesses to having broken in to the house but not having fired the weapon. He refuses to name any accomplices. Suspect 2 refuses to comment, despite glass-covered clothing being found within a plastic bag in a bin at his residence. After further testing, this clothing was also found to be covered in gunshot-residue particles. No weapon is recovered.

Here are three facts-in-issue of the (probably) many for this case at this preliminary stage. 

Fact-in-issue 1: whether or not Suspect 2 killed the victim with the intent to kill or cause grievous bodily harm.

- $H_p^1$: Suspect 2 committed murder,
- $H_d^1$: Suspect 2 did not commit murder,

Fact-in-issue 2: whether or not Suspect 2 fired the gun in question

- $H_p^2$: Suspect 2 fired the gun,
- $H_d^2$: Suspect 2 did not fire the gun,

Fact-in-issue 3: whether or not the glass fragments found on Suspect 2's clothing originated from the smashed window

- $H_p^3$: The glass fragments originate from the smashed window,
- $H_d^3$: The glass fragments originate from a source other than the smashed window.

We have extracted the information from the case scenario and formulated potential facts-in-issue. These facts-in-issue isolate individual issues that appear in the case scenario. They also make a clear statement about what is the potential issue which surrounds each fact, e.g. was it or was it not the suspect?

It is clear that for each fact-in-issue, we have created a potential pair of competing propositions. Each proposition makes a direct assertion about the associated fact-in-issue, considers each side of the issue (prosecution or defence) separately, and is either true or false. Using this process reduces complex case scenarios into individual unambiguous points of focus, around which the investigation can be anchored.

There are some other key properties of these propositions which are worth exploring. Let's revisit the following competing pair of propositions:

- $H_p^2$: Suspect 2 fired the gun,
- $H_d^2$: Suspect 2 did not fire the gun.

One property of these propositions is that when one is true, the other is necessarily false (and vice versa). They cannot both be true. This is known as **mutual exclusivity**. Mutual exclusivity occurs when two propositions make assertions which have logical no overlap. Suspect 2 firing the gun and not firing the gun cannot both be true, they are completely seperable assertions.

Another property of these propositions is that either one or the other must be true -- there is no scenario in which both are false. This is known as **exhaustivity**. Exhaustivity means that the propositions cover the entire set of all possibilities for the event in question. We know that a gun was fired, so either Suspect 2 fired the gun or they did not. The proposition $H_p^2$ covers one specific event and $H_d^2$ covers everything else. 

When competing propositions are exhaustive and mutually exclusive then they cover all possible events, meaning that one of them must be true, but they cannot both be true. This means that one of the propositions must be true and the other must be false. This 'either one or the other' property makes such competing propositions easier to evaluate, since knowing the truth of one determines the truth of the other.

These propositions were guaranteed to be mutually exclusive and exhaustive because of the way we constructed them. First we specified $H_p$. Then, we **negated** $H_p$ to get $H_d$ in each pair of propositions. A simpler way of phrasing this is to say we formed '$H_p$' and 'not $H_p$'. Take the glass propositions as an example:

- $H_p^3$: The glass fragments originate from the smashed window,
- $H_d^3$: The glass fragments originate from a source other than the smashed window.

If $H_p^3$ is not true, then the glass fragments must originate from a source other than the smashed window, and so we get $H_d^3$. This makes the propositions necessarily mutually exclusive, '$H_p^3$' and 'not $H_p^3$' cannot both be true because they are logical negations. It also means that they are exhaustive, since $H_p^3$ or its negation ('anything else') must be true.

The logic of negating propositions is in line with the burden of proof in UK criminal cases. It is for the prosecution to prove beyond reasonable doubt that their assertions are true. The defence, in proving reasonable doubt about the prosecution assertions need only show that the opposite of the prosecution story has reasonable credibility. Negating prosecution propositions is one logical way of doing this.

There are plenty of situations in which simply negating the prosecution propositions is inappropriate however, e.g. when the defendant has a genuine alternative narrative for events. In this situation, the defence narrative might be used for $H_d$, e.g.:

- $H_d^3$: the glass fragments originate from a glass barrier at a shooting range that Suspect 2 has recently been performing construction work on.

This proposition is still competing with $H_p^3$, and $H_p^3$ and the new $H_d^3$ are still mutually exclusive. However, they are no longer exhaustive. This is because all possible alternatives to $H_p^3$ are no longer considered by $H_d^3$. In other words, it is now possible for both $H_p^3$ and $H_d^3$ to be false. This could happen if the suspect lies or is mistaken about their alternative version of events.

These properties of propositions are important when we begin to consider probabilities associated with them in Chapter [...]. But first we will look at different categories of proposition. 

## Hierarchy of propositions

It's helpful to further categorise propositions based upon the type of assertion that they are making. 

offence

activity

source

sub-source

## Probative value of evidence

evidence conditioned on propositions

## Changing propositions

## More information

## Exercises